# Use Node 18 as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install Node.js dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Expose port 3004 for the server
EXPOSE 3004

# Start the Node.js server
CMD ["node", "src/server.js"]
